kind = "mobile"
previewPath = "/"
title = "نداء شايلد"
version = "1.0.0"
id = "artifacts/nidaa-shield"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 24958

[services.development]
run = "pnpm --filter @workspace/nidaa-shield run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nidaa-shield", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/nidaa-shield", "run", "serve" ]

[services.env]
PORT = "24958"
BASE_PATH = "/"
